/**
 * Shared Enums
 *
 * All enums used across backend and frontend.
 * Keep in sync with Prisma schema enums.
 */

export enum UserRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  STAFF = 'STAFF',
  CLIENT = 'CLIENT',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
}

export enum ReservationStatus {
  HOLD = 'HOLD',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  VALIDATED = 'VALIDATED',
  REJECTED = 'REJECTED',
}

export enum RatePlanType {
  HOURLY = 'HOURLY',
  DAILY = 'DAILY',
  MONTHLY = 'MONTHLY',
}

export enum DiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED = 'FIXED',
}

export enum AuditAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  WORKSPACE_UPDATED = 'WORKSPACE_UPDATED',
  ROOM_CREATED = 'ROOM_CREATED',
  ROOM_UPDATED = 'ROOM_UPDATED',
  ROOM_DELETED = 'ROOM_DELETED',
  RATE_PLAN_CREATED = 'RATE_PLAN_CREATED',
  RATE_PLAN_UPDATED = 'RATE_PLAN_UPDATED',
  RATE_PLAN_DELETED = 'RATE_PLAN_DELETED',
  RESERVATION_CREATED = 'RESERVATION_CREATED',
  RESERVATION_CONFIRMED = 'RESERVATION_CONFIRMED',
  RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
  RESERVATION_EXPIRED = 'RESERVATION_EXPIRED',
  PAYMENT_UPLOADED = 'PAYMENT_UPLOADED',
  PAYMENT_VALIDATED = 'PAYMENT_VALIDATED',
  PAYMENT_REJECTED = 'PAYMENT_REJECTED',
}
